version: '3.1'

services:
  database:
    image: mariadb:10.6.4-focal
    restart: on-failure
    ports:
      - 3307:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - spring-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/spring_data
      SPRING_DATASOURCE_USERNAME: '${MYSQL_USER}'
      SPRING_DATASOURCE_PASSWORD: '${MYSQL_PASSWORD}'
    depends_on:
      - database
    networks:
      - spring-network

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge